language: node_js
node_js:
  - "7"

sudo: required

branches:
  only: 
    - feature/Prodotto

notifications:
  email: false

cache: npm

before_script:
  - cd ./Codice

script:
  - cd ./GrafanaAndBayes
  - npm install
  - npm run test
  - npm run codecov
  - cd ../Server
  - npm install
  - npm run test
  - npm run codecov
